# Variables
PYTHON = python3

# Regla para ejecutar el archivo Bolos.py
run:
	python3 Bolos.py

# Regla para ejecutar los tests en el archivo TestBolos.py
test:
	python3 -m unittest discover -s . -p "Test*.py"

# Regla por defecto
default: run