# Makefile para ejecutar cliserv2.py

# Detectar la versión de Python
PYTHON := $(shell command -v python3 || command -v python || echo "Python no encontrado")

# Regla para ejecutar el script
run:
	@echo "Usando Python: $(PYTHON)"
	$(PYTHON) cliserv2.py
