# Makefile para ejecutar serv3.py y cli3.py

# Detectar la versión de Python
PYTHON := $(shell command -v python3 || command -v python || echo "Python no encontrado")

# Regla para ejecutar el servidor
servidor:
	$(PYTHON) serv4.py

# Regla para ejecutar el cliente
cliente:
	$(PYTHON) cli4.py
